### ISSUE TITLE
Dispatch directive pfails with missing search_image_for_language()

### ISSUE THREAD

**Issue by ankostis** [vinci1it2000/schedula#3]
Building sites with dispatch directive fails (see [co2mpas build](https://readthedocs.org/projects/co2mpas-ta/builds/4925281/))

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/dev/lib/python3.4/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/dev/lib/python3.4/site-packages/sphinx/application.py", line 266, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/dev/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))

[...]

  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/dev/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 2311, in explicit_construct
    return method(self, expmatch)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/dev/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 2054, in directive
    directive_class, match, type_name, option_presets)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/dev/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 2103, in run_directive
    result = directive_instance.run()
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/dev/lib/python3.4/site-packages/schedula/ext/dispatcher.py", line 255, in run
    argument = search_image_for_language(self.arguments[0], env)
NameError: name 'search_image_for_language' is not defined

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/dev/lib/python3.4/site-packages/schedula/ext/dispatcher.py", line 255, in run
    argument = search_image_for_language(self.arguments[0], env)
NameError: name 'search_image_for_language' is not defined
```

It seems that `search_image_for_language()` was introduced since [sphinx-1.4+](http://www.sphinx-doc.org/en/1.3.1/_modules/sphinx/environment.html).
So an appropriate versioned-dependency must be set in this project.
(please remove `import *` occurrences, it makes things difficult to debug, [among others](http://stackoverflow.com/questions/2386714/why-is-import-bad)).

**Comment by vinci1it2000** [comment]
This has been fixed with a try.. except.. in 9ebc1e359214ab5af6433a479aaedf0cd94756f3.
