### ISSUE TITLE
Site fails with sphinx 1.6.2

### ISSUE THREAD

**Issue by ankostis** [vinci1it2000/schedula#7]
In [Build #5601384](https://readthedocs.org/projects/co2mpas-ta/builds/5601384/), co2mpas's site has failed because sphinx is upgraded to `1.6.2` - when pinned to 1.5.5 it worked.

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/sphinx/application.py", line 196, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/sphinx/application.py", line 456, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/sphinx/registry.py", line 207, in load_extension
    metadata = mod.setup(app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/schedula/ext/autosummary.py", line 196, in setup
    listeners = app._listeners[event]
AttributeError: 'Sphinx' object has no attribute '_listeners'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/schedula/ext/autosummary.py", line 196, in setup
    listeners = app._listeners[event]
AttributeError: 'Sphinx' object has no attribute '_listeners'
```

**Comment by vinci1it2000** [comment]
Fixed. With Sphinx 1.6.2 the listeners have been moved in EventManager.

**Comment by ankostis** [comment]
Have you updated  `[co2mpas]/requirements/dev.pip` file now that you fixed that?
